#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


// Combos //

enum combos {
	WF_AUml,
	FP_SUml,
	LU_UUml,
	UY_OUml,
	YScln_Quot,
	CD_Tab,
	HComm_EUR,
	MinsEql_Grv,
	ZRAX_CtrlX,
	RAXC_CtrlC,
	CV_CtrlV,
};

const uint16_t PROGMEM wf_combo[] = {KC_W, KC_F, COMBO_END};
const uint16_t PROGMEM fp_combo[] = {KC_F, KC_P, COMBO_END};
const uint16_t PROGMEM lu_combo[] = {KC_L, KC_U, COMBO_END};
const uint16_t PROGMEM uy_combo[] = {KC_U, KC_Y, COMBO_END};
const uint16_t PROGMEM yscln_combo[] = {KC_Y, KC_SCLN, COMBO_END};
const uint16_t PROGMEM cd_combo[] = {KC_C, KC_D, COMBO_END};
const uint16_t PROGMEM hcomm_combo[] = {KC_H, KC_COMM, COMBO_END};
const uint16_t PROGMEM minseql_combo[] = {KC_MINS, KC_EQL, COMBO_END};
const uint16_t PROGMEM zrax_combo[] = {KC_Z, RALT_T(KC_X), COMBO_END};
const uint16_t PROGMEM raxc_combo[] = {RALT_T(KC_X), KC_C, COMBO_END};
const uint16_t PROGMEM cv_combo[] = {KC_C, KC_V, COMBO_END};

combo_t key_combos[] = {
  [WF_AUml] = COMBO(wf_combo, RALT(KC_Q)),
  [FP_SUml] = COMBO(fp_combo, RALT(KC_S)),
  [LU_UUml] = COMBO(lu_combo, RALT(KC_Y)),
  [UY_OUml] = COMBO(uy_combo, RALT(KC_P)),
  [YScln_Quot] = COMBO(yscln_combo, KC_QUOT),
  [CD_Tab] = COMBO(cd_combo, KC_TAB),
  [HComm_EUR] = COMBO(hcomm_combo, RALT(KC_5)),
  [MinsEql_Grv] = COMBO(minseql_combo, KC_V),
  [ZRAX_CtrlX] = COMBO(zrax_combo, LCTL(KC_X)),
  [RAXC_CtrlC] = COMBO(raxc_combo, LCTL(KC_C)),
  [CV_CtrlV] = COMBO(cv_combo, LCTL(KC_V)),
};


// Keymap //

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_Q, KC_W, KC_F, KC_P, KC_B, KC_NO, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, LGUI_T(KC_A), LALT_T(KC_R), LSFT_T(KC_S), LCTL_T(KC_T), KC_G, KC_M, RCTL_T(KC_N), RSFT_T(KC_E), LALT_T(KC_I), RGUI_T(KC_O), KC_Z, RALT_T(KC_X), KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, RALT_T(KC_DOT), KC_SLSH, KC_BSPC, LT(2,KC_ENT), LT(1,KC_SPC), KC_TAB),
	[1] = LAYOUT(RSFT(KC_1), RSFT(KC_2), RSFT(KC_3), RSFT(KC_4), RSFT(KC_5), KC_NO, LSFT(KC_6), LSFT(KC_7), LSFT(KC_8), LSFT(KC_9), LSFT(KC_0), LGUI_T(KC_1), LALT_T(KC_2), LSFT_T(KC_3), LCTL_T(KC_4), KC_5, KC_6, RCTL_T(KC_7), RSFT_T(KC_8), LALT_T(KC_9), RGUI_T(KC_0), KC_MINS, RALT_T(KC_QUOT), KC_EQL, KC_LPRN, KC_LBRC, KC_RBRC, KC_RPRN, KC_COMM, RALT_T(KC_DOT), KC_BSLS, KC_TRNS, MO(3), KC_NO, KC_NO),
	[2] = LAYOUT(KC_ESC, KC_PSCR, KC_UP, KC_INS, KC_PGUP, KC_TRNS, RGB_HUI, RGB_SAI, RGB_VAI, KC_NO, RGB_SPI, KC_HOME, KC_LEFT, KC_DOWN, KC_RGHT, KC_END, RGB_MOD, KC_RCTL, KC_RSFT, KC_LALT, KC_RGUI, KC_SCRL, KC_PAUS, KC_APP, KC_DEL, KC_PGDN, RGB_HUD, RGB_SAD, RGB_VAD, KC_RALT, RGB_SPD, KC_NO, KC_NO, TT(4), RGB_TOG),
	[3] = LAYOUT(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_NO, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, KC_F11, KC_F12, KC_RCTL, KC_RSFT, KC_LALT, KC_RGUI, KC_NO, KC_RALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
	[4] = LAYOUT(TT(4), KC_BTN1, KC_MS_U, KC_BTN2, KC_WH_U, KC_NO, KC_PSLS, KC_7, KC_8, KC_9, KC_PMNS, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_BTN3, KC_PAST, KC_4, KC_5, KC_6, KC_PPLS, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_D, KC_NO, KC_1, KC_2, KC_3, KC_COMM, KC_BSPC, KC_ENT, KC_SPC, KC_0)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




