VIA_ENABLE		= yes
VIAL_ENABLE		= yes

RGB_MATRIX_ENABLE	= yes
COMBO_ENABLE		= yes
BACKLIGHT_ENABLE	= yes
MOUSEKEY_ENABLE		= yes
OLED_ENABLE		= yes
TAP_DANCE_ENABLE	= yes
QMK_SETTINGS		= yes
EXTRAKEY_ENABLE		= yes

CONVERT_TO		= helios
